# Dish Parameters
PETRI_DISH_HEIGHT = 600
PETRI_DISH_WIDTH = 1200

# Movement Parameters
SHOCK_CLOCK = 20
RESET_CLOCK = 200

# Microbe Parameters
MICROBE_RADIUS = 18
MICROBE_MAX_VISION_FIELD = 3

# Bouncer Parameters
BOUNCER_SPEED = 0.02
BOUNCER_RADIUS = 65

# Food Parameters
FOOD_SPEED = 0.08
FOOD_RADIUS = 10

# Snack Parameters
SNACK_SPEED = 0.04
SNACK_RADIUS = 5