from PetriDish import PetriDish

#microbe1 = Microbe(300, 100)
#microbe2 = Microbe(320, 100)
#microbe3 = Microbe(300, 120)
#microbe4 = Microbe(300, 100)
#microbe4.setParents(microbe1, microbe2)
#microbe5 = Microbe(320, 100)
#microbe5.setParents(microbe2, microbe3)
#microbe6 = Microbe(300, 120)
#microbe6.setParents(microbe4, microbe5)
#print(microbe.getMyX(), microbe.getMyY())
#print(microbe.sight1.getVisionX(), microbe.sight1.getVisionY())
#print(microbe.sight2.getVisionX(), microbe.sight2.getVisionY())
#print(microbe.sight3.getVisionX(), microbe.sight3.getVisionY())
#print(microbe.sight4.getVisionX(), microbe.sight4.getVisionY())
#print(microbe.sight5.getVisionX(), microbe.sight5.getVisionY())
#print(microbe.sight6.getVisionX(), microbe.sight6.getVisionY())
#print(microbe.sight7.getVisionX(), microbe.sight7.getVisionY())
#print(microbe1.toString())
#print("========================================================================")
#print(microbe2.toString())
#print("========================================================================")
#print(microbe3.toString())
#print("========================================================================")
#print(microbe4.toString())
#print("========================================================================")
#print(microbe5.toString())
#print("========================================================================")
#print(microbe6.toString())



petriDish = PetriDish()
petriDish.setup()
petriDish.visualizeDish()